// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCareerPlatform;

#nullable disable

namespace SmartCareerPlatform.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250724025915_AddCourseFields")]
    partial class AddCourseFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCareerPlatform.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<string>>("RelatedSkills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2580),
                            Description = "Dynamic programming language for web development",
                            Name = "JavaScript",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2580),
                            Description = "General-purpose programming language",
                            Name = "Python",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2580),
                            Description = "Object-oriented programming language",
                            Name = "Java",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 4,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2580),
                            Description = "Microsoft's object-oriented programming language",
                            Name = "C#",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 5,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2580),
                            Description = "Typed superset of JavaScript",
                            Name = "TypeScript",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 6,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Google's systems programming language",
                            Name = "Go",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 7,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Systems programming language focused on safety",
                            Name = "Rust",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 8,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Extension of C programming language",
                            Name = "C++",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 9,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Server-side scripting language",
                            Name = "PHP",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 10,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Dynamic programming language",
                            Name = "Ruby",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 11,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Apple's programming language for iOS/macOS",
                            Name = "Swift",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 12,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Modern programming language for Android",
                            Name = "Kotlin",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 13,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Functional and object-oriented programming language",
                            Name = "Scala",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 14,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Statistical computing language",
                            Name = "R",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 15,
                            Category = "Programming Languages",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Numerical computing language",
                            Name = "MATLAB",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 16,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "JavaScript library for building user interfaces",
                            Name = "React",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 17,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Progressive JavaScript framework",
                            Name = "Vue.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 18,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2590),
                            Description = "TypeScript-based web application framework",
                            Name = "Angular",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 19,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Markup language for web pages",
                            Name = "HTML5",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 20,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Stylesheet language for web design",
                            Name = "CSS3",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 21,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "CSS preprocessor",
                            Name = "SASS/SCSS",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 22,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "CSS framework for responsive design",
                            Name = "Bootstrap",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 23,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Utility-first CSS framework",
                            Name = "Tailwind CSS",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 24,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "JavaScript library for DOM manipulation",
                            Name = "jQuery",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 25,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Module bundler for JavaScript applications",
                            Name = "Webpack",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 26,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Fast build tool for modern web projects",
                            Name = "Vite",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 27,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "React framework for production",
                            Name = "Next.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 28,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Vue.js framework for universal applications",
                            Name = "Nuxt.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 29,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Compile-time framework for web apps",
                            Name = "Svelte",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 30,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "State management library for JavaScript apps",
                            Name = "Redux",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 31,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "JavaScript runtime for server-side development",
                            Name = "Node.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 32,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2600),
                            Description = "Web framework for Node.js",
                            Name = "Express.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 33,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Python web framework",
                            Name = "Django",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 34,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Lightweight Python web framework",
                            Name = "Flask",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 35,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Java framework for building applications",
                            Name = "Spring Boot",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 36,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Microsoft's web framework",
                            Name = "ASP.NET Core",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 37,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Ruby web framework",
                            Name = "Ruby on Rails",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 38,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "PHP web framework",
                            Name = "Laravel",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 39,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Modern Python web framework",
                            Name = "FastAPI",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 40,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "HTTP web framework for Go",
                            Name = "Gin",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 41,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Express-inspired web framework for Go",
                            Name = "Fiber",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 42,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Actor framework for Rust",
                            Name = "Actix",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 43,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Node.js framework for scalable applications",
                            Name = "Nest.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 44,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Next generation web framework for Node.js",
                            Name = "Koa.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 45,
                            Category = "Backend",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Rich framework for building applications",
                            Name = "Hapi.js",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 46,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Structured Query Language",
                            Name = "SQL",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 47,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Open source relational database",
                            Name = "PostgreSQL",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 48,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Popular relational database",
                            Name = "MySQL",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 49,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "NoSQL document database",
                            Name = "MongoDB",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 50,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "In-memory data structure store",
                            Name = "Redis",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 51,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Lightweight relational database",
                            Name = "SQLite",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 52,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Enterprise relational database",
                            Name = "Oracle",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 53,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Distributed NoSQL database",
                            Name = "Cassandra",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 54,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "AWS NoSQL database service",
                            Name = "DynamoDB",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 55,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Search and analytics engine",
                            Name = "Elasticsearch",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 56,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Graph database platform",
                            Name = "Neo4j",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 57,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Time series database",
                            Name = "InfluxDB",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 58,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Document-oriented NoSQL database",
                            Name = "CouchDB",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 59,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Microsoft's relational database",
                            Name = "Microsoft SQL Server",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 60,
                            Category = "Database",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Google's mobile and web development platform",
                            Name = "Firebase",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 61,
                            Category = "Cloud",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Amazon Web Services cloud platform",
                            Name = "AWS",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 62,
                            Category = "Cloud",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Microsoft's cloud computing platform",
                            Name = "Azure",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 63,
                            Category = "Cloud",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Google's cloud computing services",
                            Name = "Google Cloud",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 64,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Containerization platform",
                            Name = "Docker",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 65,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Container orchestration platform",
                            Name = "Kubernetes",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 66,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Automation server for CI/CD",
                            Name = "Jenkins",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 67,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "GitLab's CI/CD platform",
                            Name = "GitLab CI",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 68,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "GitHub's CI/CD platform",
                            Name = "GitHub Actions",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 69,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Infrastructure as Code tool",
                            Name = "Terraform",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 70,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Configuration management tool",
                            Name = "Ansible",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 71,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Configuration management platform",
                            Name = "Chef",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 72,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Configuration management tool",
                            Name = "Puppet",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 73,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Development environment manager",
                            Name = "Vagrant",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 74,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Web server and reverse proxy",
                            Name = "Nginx",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 75,
                            Category = "DevOps",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Web server software",
                            Name = "Apache",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 76,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Cross-platform mobile development",
                            Name = "React Native",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 77,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2670),
                            Description = "Google's UI toolkit for mobile apps",
                            Name = "Flutter",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 78,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Native iOS app development",
                            Name = "iOS Development",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 79,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Native Android app development",
                            Name = "Android Development",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 80,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Microsoft's cross-platform framework",
                            Name = "Xamarin",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 81,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Hybrid mobile app development",
                            Name = "Cordova",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 82,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Cross-platform mobile framework",
                            Name = "Ionic",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 83,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Game development platform",
                            Name = "Unity",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 84,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Game development engine",
                            Name = "Unreal Engine",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 85,
                            Category = "Mobile",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Apple's augmented reality framework",
                            Name = "ARKit",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 86,
                            Category = "AI/ML",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Algorithms that learn from data",
                            Name = "Machine Learning",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 87,
                            Category = "AI/ML",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Neural networks with multiple layers",
                            Name = "Deep Learning",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 88,
                            Category = "AI/ML",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Open source ML platform",
                            Name = "TensorFlow",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 89,
                            Category = "AI/ML",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Deep learning framework",
                            Name = "PyTorch",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 90,
                            Category = "AI/ML",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Machine learning library for Python",
                            Name = "Scikit-learn",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 91,
                            Category = "Data Science",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Data manipulation library",
                            Name = "Pandas",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 92,
                            Category = "Data Science",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Numerical computing library",
                            Name = "NumPy",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 93,
                            Category = "Data Science",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Data visualization library",
                            Name = "Matplotlib",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 94,
                            Category = "Data Science",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Statistical data visualization",
                            Name = "Seaborn",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 95,
                            Category = "Data Science",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Interactive computing environment",
                            Name = "Jupyter",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 96,
                            Category = "Big Data",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Unified analytics engine",
                            Name = "Apache Spark",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 97,
                            Category = "Big Data",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Distributed storage and processing",
                            Name = "Hadoop",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 98,
                            Category = "Big Data",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Distributed streaming platform",
                            Name = "Kafka",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 99,
                            Category = "Data Visualization",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Data visualization software",
                            Name = "Tableau",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 100,
                            Category = "Data Visualization",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Microsoft's business analytics tool",
                            Name = "Power BI",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 101,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "JavaScript testing framework",
                            Name = "Jest",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 102,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "End-to-end testing framework",
                            Name = "Cypress",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 103,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Web browser automation",
                            Name = "Selenium",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 104,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2700),
                            Description = "Unit testing framework for Java",
                            Name = "JUnit",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 105,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2700),
                            Description = "Testing framework for Python",
                            Name = "PyTest",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 106,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2700),
                            Description = "JavaScript test framework",
                            Name = "Mocha",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 107,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2700),
                            Description = "Behavior-driven testing framework",
                            Name = "Jasmine",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 108,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2700),
                            Description = "Testing framework for Java",
                            Name = "TestNG",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 109,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2700),
                            Description = "API testing platform",
                            Name = "Postman",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 110,
                            Category = "Testing",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "API testing tool",
                            Name = "Insomnia",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 111,
                            Category = "Version Control",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Distributed version control system",
                            Name = "Git",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 112,
                            Category = "Version Control",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Git repository hosting service",
                            Name = "GitHub",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 113,
                            Category = "Version Control",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Git repository management platform",
                            Name = "GitLab",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 114,
                            Category = "Version Control",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Git repository hosting service",
                            Name = "Bitbucket",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 115,
                            Category = "Version Control",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Centralized version control system",
                            Name = "SVN",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 116,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Code editor by Microsoft",
                            Name = "VS Code",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 117,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Java IDE by JetBrains",
                            Name = "IntelliJ IDEA",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 118,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Microsoft's IDE",
                            Name = "Visual Studio",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 119,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Text editor for code",
                            Name = "Sublime Text",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 120,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Text editor",
                            Name = "Vim",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 121,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Planning and executing projects",
                            Name = "Project Management",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 122,
                            Category = "Methodology",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Iterative development methodology",
                            Name = "Agile",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 123,
                            Category = "Methodology",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Agile framework for project management",
                            Name = "Scrum",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 124,
                            Category = "Methodology",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Visual workflow management",
                            Name = "Kanban",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 125,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Guiding and inspiring teams",
                            Name = "Leadership",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 126,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Effective information exchange",
                            Name = "Communication",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 127,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Analytical thinking and solutions",
                            Name = "Problem Solving",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 128,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Working effectively with others",
                            Name = "Team Collaboration",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 129,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Efficiently managing time and tasks",
                            Name = "Time Management",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 130,
                            Category = "Soft Skills",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Objective analysis and evaluation",
                            Name = "Critical Thinking",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 131,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Protecting digital systems",
                            Name = "Cybersecurity",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 132,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Simulated cyber attacks",
                            Name = "Penetration Testing",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 133,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2720),
                            Description = "Secure communication techniques",
                            Name = "Cryptography",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 134,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Protecting network infrastructure",
                            Name = "Network Security",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 135,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Web application security",
                            Name = "OWASP",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 136,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Authorization framework",
                            Name = "OAuth",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 137,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "JSON Web Tokens",
                            Name = "JWT",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 138,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Secure communication protocols",
                            Name = "SSL/TLS",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 139,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Network security system",
                            Name = "Firewall",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 140,
                            Category = "Security",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Identifying security weaknesses",
                            Name = "Vulnerability Assessment",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 141,
                            Category = "Emerging Tech",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Distributed ledger technology",
                            Name = "Blockchain",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 142,
                            Category = "Emerging Tech",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Smart contract programming language",
                            Name = "Solidity",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 143,
                            Category = "Emerging Tech",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Internet of Things development",
                            Name = "IoT",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 144,
                            Category = "Emerging Tech",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Augmented and Virtual Reality",
                            Name = "AR/VR",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 145,
                            Category = "Emerging Tech",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Quantum-mechanical computing",
                            Name = "Quantum Computing",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 146,
                            Category = "Emerging Tech",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Distributed computing paradigm",
                            Name = "Edge Computing",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 147,
                            Category = "Architecture",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2730),
                            Description = "Distributed system architecture",
                            Name = "Microservices",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 148,
                            Category = "API",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2740),
                            Description = "Query language for APIs",
                            Name = "GraphQL",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 149,
                            Category = "API",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2740),
                            Description = "Representational State Transfer",
                            Name = "REST API",
                            RelatedSkills = new List<string>()
                        },
                        new
                        {
                            Id = 150,
                            Category = "API",
                            CreatedAt = new DateTime(2025, 7, 24, 2, 59, 14, 922, DateTimeKind.Utc).AddTicks(2740),
                            Description = "Real-time communication protocol",
                            Name = "WebSockets",
                            RelatedSkills = new List<string>()
                        });
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCourse");
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.UserCourseInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCourseInteractions");
                });

            modelBuilder.Entity("UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills", (string)null);
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.Enrollment", b =>
                {
                    b.HasOne("SmartCareerPlatform.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCareerPlatform.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.UserCourse", b =>
                {
                    b.HasOne("SmartCareerPlatform.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCareerPlatform.Models.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.UserCourseInteraction", b =>
                {
                    b.HasOne("SmartCareerPlatform.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCareerPlatform.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserSkill", b =>
                {
                    b.HasOne("SmartCareerPlatform.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCareerPlatform.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("SmartCareerPlatform.Models.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("UserCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
